CREATE TABLE IF NOT EXISTS `crimes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `reported_date` varchar(50) NOT NULL,
  `suburb_incident` varchar(50) NOT NULL,
  `postcode_incident` int(11) NOT NULL,
  `offence_level_1` varchar(250) NOT NULL,
  `offence_level_2` varchar(250) NOT NULL,
  `offence_level_3` varchar(250) NOT NULL,
  `offence_count` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (1,'01/07/2019','ADELAIDE',5000,'OFFENCES AGAINST PROPERTY','FRAUD DECEPTION AND RELATED OFFENCES','Obtain benefit by deception',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (2,'01/07/2019','ADELAIDE',5000,'OFFENCES AGAINST PROPERTY','FRAUD DECEPTION AND RELATED OFFENCES','Other fraud, deception and related offences',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (3,'01/07/2019','ADELAIDE',5000,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Graffiti',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (4,'01/07/2019','ADELAIDE',5000,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',2);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (5,'01/07/2019','ADELAIDE',5000,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',6);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (6,'01/07/2019','ADELAIDE',5000,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',2);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (7,'01/07/2019','ADELAIDE',5000,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from shop',5);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (8,'01/07/2019','ADELAIDE',5000,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Common Assault',3);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (9,'01/07/2019','ADELAIDE',5000,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Serious Assault not resulting in injury',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (10,'01/07/2019','ADELAIDE AIRPORT',5950,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (11,'01/07/2019','ALBERTON',5014,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (12,'01/07/2019','ANDREWS FARM',5114,'OFFENCES AGAINST PROPERTY','FRAUD DECEPTION AND RELATED OFFENCES','Other fraud, deception and related offences',2);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (13,'01/07/2019','ANDREWS FARM',5114,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Serious Assault not resulting in injury',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (14,'01/07/2019','ANGASTON',5353,'OFFENCES AGAINST PROPERTY','FRAUD DECEPTION AND RELATED OFFENCES','Other fraud, deception and related offences',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (15,'01/07/2019','ANGLE VALE',5117,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from shop',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (16,'01/07/2019','ATHOL PARK',5012,'OFFENCES AGAINST PROPERTY','SERIOUS CRIMINAL TRESPASS','SCT - Non Residence',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (17,'01/07/2019','BANKSIA PARK',5091,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Property damage by fire or explosion',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (18,'01/07/2019','BASKET RANGE',5138,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Serious Assault not resulting in injury',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (19,'01/07/2019','BERRI',5343,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (20,'01/07/2019','BERRI',5343,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Common Assault',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (21,'01/07/2019','BEVERLEY',5009,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Graffiti',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (22,'01/07/2019','BEVERLEY',5009,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (23,'01/07/2019','BIRKENHEAD',5015,'OFFENCES AGAINST PROPERTY','SERIOUS CRIMINAL TRESPASS','SCT - Residence',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (24,'01/07/2019','BLAIR ATHOL',5084,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',2);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (25,'01/07/2019','BLAIR ATHOL',5084,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (26,'01/07/2019','BLAKEVIEW',5114,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from shop',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (27,'01/07/2019','BLANCHETOWN',5357,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (28,'01/07/2019','BOORS PLAIN',5554,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Receive or handle proceeds of crime',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (29,'01/07/2019','BOWDEN',5007,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Serious Assault resulting in injury',2);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (30,'01/07/2019','BRIGHTON',5048,'OFFENCES AGAINST PROPERTY','FRAUD DECEPTION AND RELATED OFFENCES','Other fraud, deception and related offences',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (31,'01/07/2019','BURNSIDE',5066,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft/Illegal Use of MV',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (32,'01/07/2019','CAMBRAI',5353,'OFFENCES AGAINST PROPERTY','SERIOUS CRIMINAL TRESPASS','SCT - Non Residence',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (33,'01/07/2019','CAMDEN PARK',5038,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Serious Assault not resulting in injury',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (34,'01/07/2019','CAMPBELLTOWN',5074,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (35,'01/07/2019','CHRISTIE DOWNS',5164,'OFFENCES AGAINST PROPERTY','SERIOUS CRIMINAL TRESPASS','Other unlawful entry with intent',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (36,'01/07/2019','CHRISTIE DOWNS',5164,'OFFENCES AGAINST PROPERTY','SERIOUS CRIMINAL TRESPASS','SCT - Residence',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (37,'01/07/2019','CHRISTIES BEACH',5165,'OFFENCES AGAINST PROPERTY','SERIOUS CRIMINAL TRESPASS','SCT - Residence',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (38,'01/07/2019','CLARENCE GARDENS',5039,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (39,'01/07/2019','CLEARVIEW',5085,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (40,'01/07/2019','CLEARVIEW',5085,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',2);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (41,'01/07/2019','COLLINSWOOD',5081,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (42,'01/07/2019','COOBER PEDY',5723,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Serious Assault not resulting in injury',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (43,'01/07/2019','COWANDILLA',5033,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (44,'01/07/2019','CRAIGMORE',5114,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',2);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (45,'01/07/2019','CRAIGMORE',5114,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Common Assault',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (46,'01/07/2019','CROYDON PARK',5008,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft/Illegal Use of MV',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (47,'01/07/2019','DAVOREN PARK',5113,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',2);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (48,'01/07/2019','DAVOREN PARK',5113,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',2);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (49,'01/07/2019','DAW PARK',5041,'OFFENCES AGAINST PROPERTY','SERIOUS CRIMINAL TRESPASS','SCT - Residence',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (50,'01/07/2019','DOVER GARDENS',5048,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (51,'01/07/2019','DOVER GARDENS',5048,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (52,'01/07/2019','DOVER GARDENS',5048,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Other acts intended to cause injury',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (53,'01/07/2019','DULWICH',5065,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Common Assault',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (54,'01/07/2019','EDEN HILLS',5050,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (55,'01/07/2019','EDWARDSTOWN',5039,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (56,'01/07/2019','EDWARDSTOWN',5039,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from shop',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (57,'01/07/2019','ELIZABETH DOWNS',5113,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (58,'01/07/2019','ELIZABETH DOWNS',5113,'OFFENCES AGAINST PROPERTY','SERIOUS CRIMINAL TRESPASS','Other unlawful entry with intent',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (59,'01/07/2019','ELIZABETH DOWNS',5113,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft/Illegal Use of MV',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (60,'01/07/2019','ELIZABETH DOWNS',5113,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Common Assault',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (61,'01/07/2019','ELIZABETH EAST',5112,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (62,'01/07/2019','ELIZABETH GROVE',5112,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (63,'01/07/2019','ELIZABETH GROVE',5112,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (64,'01/07/2019','ELIZABETH NORTH',5113,'OFFENCES AGAINST PROPERTY','FRAUD DECEPTION AND RELATED OFFENCES','Obtain benefit by deception',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (65,'01/07/2019','ELIZABETH NORTH',5113,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (66,'01/07/2019','ELIZABETH NORTH',5113,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (67,'01/07/2019','ELIZABETH NORTH',5113,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (68,'01/07/2019','ELIZABETH NORTH',5113,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Common Assault',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (69,'01/07/2019','ENFIELD',5085,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (70,'01/07/2019','ERINDALE',5066,'OFFENCES AGAINST PROPERTY','FRAUD DECEPTION AND RELATED OFFENCES','Obtain benefit by deception',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (71,'01/07/2019','ERINDALE',5066,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (72,'01/07/2019','EVERARD PARK',5035,'OFFENCES AGAINST PROPERTY','SERIOUS CRIMINAL TRESPASS','SCT - Residence',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (73,'01/07/2019','EYRE',5121,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from shop',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (74,'01/07/2019','FELIXSTOW',5070,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Common Assault',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (75,'01/07/2019','FERRYDEN PARK',5010,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (76,'01/07/2019','FERRYDEN PARK',5010,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (77,'01/07/2019','FERRYDEN PARK',5010,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Common Assault',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (78,'01/07/2019','FERRYDEN PARK',5010,'OFFENCES AGAINST THE PERSON','OTHER OFFENCES AGAINST THE PERSON','Dangerous or negligent acts',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (79,'01/07/2019','FINDON',5023,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Property damage by fire or explosion',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (80,'01/07/2019','FINDON',5023,'OFFENCES AGAINST PROPERTY','SERIOUS CRIMINAL TRESPASS','SCT - Residence',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (81,'01/07/2019','FLINDERS PARK',5025,'OFFENCES AGAINST PROPERTY','FRAUD DECEPTION AND RELATED OFFENCES','Obtain benefit by deception',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (82,'01/07/2019','FLINDERS PARK',5025,'OFFENCES AGAINST PROPERTY','SERIOUS CRIMINAL TRESPASS','SCT - Non Residence',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (83,'01/07/2019','FLINDERS PARK',5025,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',2);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (84,'01/07/2019','FREELING',5372,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Common Assault',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (85,'01/07/2019','FREWVILLE',5063,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (86,'01/07/2019','FREWVILLE',5063,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (87,'01/07/2019','FULHAM GARDENS',5024,'OFFENCES AGAINST PROPERTY','FRAUD DECEPTION AND RELATED OFFENCES','Obtain benefit by deception',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (88,'01/07/2019','FULLARTON',5063,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (89,'01/07/2019','GAWLER',5118,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (90,'01/07/2019','GAWLER',5118,'OFFENCES AGAINST THE PERSON','ACTS INTENDED TO CAUSE INJURY','Common Assault',2);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (91,'01/07/2019','GEPPS CROSS',5094,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',4);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (92,'01/07/2019','GEPPS CROSS',5094,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from shop',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (93,'01/07/2019','GILLES PLAINS',5086,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from shop',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (94,'01/07/2019','GLENELG',5045,'OFFENCES AGAINST PROPERTY','SERIOUS CRIMINAL TRESPASS','Other unlawful entry with intent',2);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (95,'01/07/2019','GLENELG',5045,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (96,'01/07/2019','GLENELG EAST',5045,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft/Illegal Use of MV',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (97,'01/07/2019','GLENELG NORTH',5045,'OFFENCES AGAINST PROPERTY','PROPERTY DAMAGE AND ENVIRONMENTAL','Other property damage and environmental',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (98,'01/07/2019','GLENELG NORTH',5045,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from motor vehicle',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (99,'01/07/2019','GLENSIDE',5065,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Theft from shop',1);
INSERT INTO crimes(id,reported_date,suburb_incident,postcode_incident,offence_level_1,offence_level_2,offence_level_3,offence_count) VALUES (100,'01/07/2019','GOLDEN GROVE',5125,'OFFENCES AGAINST PROPERTY','THEFT AND RELATED OFFENCES','Other theft',1);